name: ci-cd

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-cd.yaml
      - src/**
      - tests/**
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-quality:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[quality]"

      - name: check-quality
        run: |
          ruff src tests
          mypy src

  run-tests:
    needs: check-quality

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[tests]"

      - name: run-tests
        run: pytest --cov=faststream_instrumentation --cov-report=term-missing tests/ -s --durations 0

  publish-package:
    needs: run-tests
    if: github.event_name == 'release'

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: build-package
        run: hatch build

      - name: publish-package
        run: hatch publish --user __token__ --auth $PYPI_TOKEN
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
